version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: harmonycare-backend
    depends_on:
      - database
    ports:
      - "48080:8080"
    restart: always

  database:
    image: mysql/mysql-server:8.0
    container_name: harmonycare-database
    environment:
      MYSQL_DATABASE: harmonycare_db
      MYSQL_USER: harmonycare_user
      MYSQL_PASSWORD: tUiEXi7yUgGAGVRHvuyg
      MYSQL_ROOT_PASSWORD: tUiEXi7yUgGAGVRHvuyg
      TZ: 'Asia/Seoul'
    expose:
      - "48081"
    ports:
      - "48081:48081"
    restart: always
    volumes:
      - harmonycare-database:/var/lib/mysql
    command:
      - --port=48081
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake

volumes:
  harmonycare-database: