spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database:48081/harmonycare_db
    username: harmonycare_user
    password: tUiEXi7yUgGAGVRHvuyg
  jwt:
    secret: kjvMLWXxW4VDgWK6Cf5QjFiDoCRrQfKDFZQQgmT8gzF2pwfQPy
  oauth2:
    google:
      token-uri: https://oauth2.googleapis.com/token
      resource-uri: https://www.googleapis.com/oauth2/v2/userinfo
      client-id: 185976520158-phphtutm302clototd3rqgecng4a4bg2.apps.googleusercontent.com
      client-secret: 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
      redirect-uri: http://localhost:8080
#      scope: profile, email

server:
  servlet:
    context-path: /api/v1
    encoding:
      charset: utf-8

logging:
  level:
    org:
    hibernate:
      SQL: DEBUG
    type:
      descriptor:
        sql:
          BasicBinder: TRACE